#!/usr/bin/env python3
"""Build-time codegen: convert src/content/blog/*.md into a single typed
TS module (src/lib/blog-content.gen.ts) so no bundler glob/tree-shake
heuristics can drop the content. Deterministic; run before `vite build`.

Wire into package.json:  "build": "python3 scripts/gen_blog_content.py && vite build"
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "src" / "content" / "blog"
OUT = ROOT / "src" / "lib" / "blog-content.gen.ts"


def main():
    files = sorted(CONTENT.glob("*.md"))
    entries = []
    for f in files:
        raw = f.read_text()
        m = re.match(r"^---\n(.*?)\n---\n(.*)$", raw, re.S)
        fm, body = (m.group(1), m.group(2)) if m else ("", raw)
        meta = {}
        for line in fm.split("\n"):
            kv = re.match(r"^(\w[\w-]*):\s*\"?(.*?)\"?\s*$", line)
            if kv:
                meta[kv[1]] = kv[2]
        slug = f.stem
        entry = {
            "slug": slug,
            "title": meta.get("title") or meta.get("keyword") or slug,
            "keyword": meta.get("keyword", ""),
            "generated": meta.get("generated", ""),
            "description": meta.get("description", ""),
            # body as a template-literal-safe JSON string is fine inside a
            # TS double-quoted string via json.dumps escaping
            "body": body.strip(),
        }
        entries.append(entry)

    lines = [
        "// AUTO-GENERATED by scripts/gen_blog_content.py - do not edit.",
        "// Source of truth: src/content/blog/*.md",
        "export interface GenPost {",
        "  slug: string;",
        "  title: string;",
        "  keyword: string;",
        "  generated: string;",
        "  description: string;",
        "  body: string;",
        "}",
        "",
        "export const GEN_POSTS: GenPost[] = [",
    ]
    for e in entries:
        lines.append("  {")
        for k, v in e.items():
            lines.append(f"    {k}: {json.dumps(v, ensure_ascii=False)},")
        lines.append("  },")
    lines.append("];")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} with {len(entries)} posts")


if __name__ == "__main__":
    main()
